### ISSUE TITLE
3DS Max shift+drag to extrude an edge

### ISSUE THREAD

**Issue by neospacian** [AtixCG/Universal-3D-Shortcuts#3]
Hello and thank you for these useful tools, 
Everything works as expected for me in 3DS Max except Shift and drag to extrude, is there a fix for this?

**Comment by AtixCG** [comment]
There is a very simple solution to this: go to Customize -> Customize User Interface -> Mouse and uncheck "Maya Mode Selection". This will allow you to use standard commands with Shift in 3DsMax, such as Extrude and Duplicate in object mode. But selection of objects will change from Shift to Ctrl. The problem here is that for some reason 3Ds Max doesn't allow you to perform these actions if selection set to Shift, although it shouldn't interfere with the selection in any way.

And thanks for your feedback and glad that the tools were helpful!

![image 16](https://user-images.githubusercontent.com/112505578/233777853-0e6e7f68-5312-417f-9b7d-207e5049bc74.png)
